### PR TITLE
Add release instructions

### PR DESCRIPTION
**Pull request by sambostock**
This adds release instructions following a discussion in Slack.

### CODE REVIEW

**Comment by elfassy** [comment]
This repo is public, we may be better off keeping these instructions somewhere private (vault?). What do you think?

**Comment by sambostock** [comment]
I think it's okay to have information for maintainers in the repo. There's precedent in other repos of ours (e.g. [`maintenance_tasks`' `README.md`](https://github.com/Shopify/maintenance_tasks/blob/main/README.md#releasing-new-versions), and others (e.g. [`rails`' `RELEASING_RAILS.md`](https://github.com/rails/rails/blob/main/RELEASING_RAILS.md)).
I'm fine with moving it to another file, if you think that makes more sense. Some patterns I've seen include a `CONTRIBUTING.md`, or `RELEASE.md`.

The Vault wouldn't be somewhere I'd look in for repo specific release instructions TBH.

**Review by elfassy — APPROVED** [review]

**Comment by elfassy** [comment]
A couple of things we could add
- update `master` branch references to `main`
- add instructions to use `git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s [%an]" | grep -iv "^Merge pull request"` to generate the release notes
- reference the vault page to make sure this is up to date, and make the updates there https://vault.shopify.io/page/Publish-a-new-version-of-an-internal-gem~dhbc57d.md

**Comment by elfassy** [comment]
Updated the copy. Will merge unless there are comments

**Pull request merged**
