### PR TITLE
Add xml serilization methods

### PR DESCRIPTION
**Pull request by cplehm**
Allow Money objects to be serialized as xml.

@vignesh-vs-in @nick-mcdonald

### CODE REVIEW

**Comment by jahfer** [comment]
Missing a test for this behaviour. Logic makes sense to me 👍

@stephenminded @maximebedard as well if you have opinions

**Comment by stephenminded** [comment]
LGTM

**Comment by cplehm** [comment]
Thanks! Added tests and bumped ruby version to fix bundle install issue in ci. @jahfer

**Comment by vignesh-vs-in** [comment]
👍

**Pull request merged**
